-- INSERT statements generated from 4.bölge.txt
-- Assumptions:
--  - region_id set to 4 (file named "4.bölge")
--  - center is "ADAPAZARI" (first column of each row)
--  - latitude and longitude are unavailable -> NULL
--  - default booleans (as in your example): has_gps=false, has_rtu=false, has_panos=false, is_active=false, is_configured=true
--  - numeric columns mapped in order:
--    security_firewall, network_switch, rtu_count, gps_card_antenna, rtu_panel, btp_panel,
--    energy_analyzer, ykgc_count, teias_rtu_installation, indoor_dome_camera,
--    network_video_management, smart_control_unit, card_reader, network_recording_unit, access_control_system

INSERT INTO locations (
  id, region_id, name, center, latitude, longitude, brand, model,
  has_gps, has_rtu, has_panos, is_active, is_configured,
  security_firewall, network_switch, rtu_count, gps_card_antenna,
  rtu_panel, btp_panel, energy_analyzer, ykgc_count, teias_rtu_installation,
  indoor_dome_camera, network_video_management, smart_control_unit,
  card_reader, network_recording_unit, access_control_system,
  transformer_center_type
) VALUES
('atasehir-gis', 4, 'ATAŞEHİR GİS', 'ADAPAZARI', NULL, NULL, 'ADVANTECH', 'SYS-4U4320-7A01',
 false, false, false, false, true,
 1, 1, 1, 0,
 0, 0, 0, 0, 0,
 1, 1, 1,
 2, 0, 0,
 'Otomasyonlu'),
('dudullu-metro-gis', 4, 'DUDULLU METRO GİS', 'ADAPAZARI', NULL, NULL, 'ADVANTECH', 'SYS-4U4320-7A01',
 false, false, false, false, true,
 1, 1, 1, 0,
 0, 0, 0, 0, 0,
 1, 1, 1,
 2, 0, 0,
 'Otomasyonlu'),
('kavacik-gis', 4, 'KAVACIK GİS', 'ADAPAZARI', NULL, NULL, 'ADVANTECH', 'SYS-4U4320-7A01',
 false, false, false, false, true,
 1, 1, 1, 0,
 0, 0, 0, 0, 0,
 1, 1, 1,
 2, 0, 0,
 'Otomasyonlu'),
('dudullu', 4, 'DUDULLU', 'ADAPAZARI', NULL, NULL, 'ABB', 'RTU560CMR01',
 false, false, false, false, true,
 1, 1, 0, 0,
 0, 0, 0, 0, 0,
 1, 1, 1,
 2, 0, 0,
 'Klasik'),
('dilisekelesi-gis', 4, 'DİLİSKELESİ GİS', 'ADAPAZARI', NULL, NULL, 'ABB', 'RTU560CMR01',
 false, false, false, false, true,
 1, 1, 0, 0,
 0, 0, 0, 0, 0,
 0, 0, 0,
 0, 0, 0,
 'Klasik'),
('gebze-osb', 4, 'GEBZE OSB', 'ADAPAZARI', NULL, NULL, 'ABB', 'RTU560CMR01',
 false, false, false, false, true,
 1, 1, 0, 0,
 0, 0, 0, 0, 0,
 0, 0, 0,
 0, 0, 0,
 'Klasik'),
('tuzla', 4, 'TUZLA', 'ADAPAZARI', NULL, NULL, 'ABB', 'RTU560CMR01',
 false, false, false, false, true,
 1, 1, 0, 0,
 0, 0, 0, 0, 0,
 0, 0, 0,
 0, 0, 0,
 'Klasik'),
('isakoy', 4, 'İSAKÖY', 'ADAPAZARI', NULL, NULL, 'ABB', 'RTU560CMR01',
 false, false, false, false, true,
 1, 1, 0, 0,
 0, 0, 0, 0, 0,
 0, 0, 0,
 0, 0, 0,
 'Klasik'),
('bostanci-metro-gis', 4, 'BOSTANCI METRO GİS', 'ADAPAZARI', NULL, NULL, 'MİKRONİKA', 'S0-52v11',
 false, false, false, false, true,
 1, 1, 0, 0,
 0, 0, 0, 0, 0,
 0, 0, 0,
 0, 0, 0,
 'Otomasyonlu'),
('tosb', 4, 'TOSB', 'ADAPAZARI', NULL, NULL, 'MİKRONİKA', 'S0-52v11',
 false, false, false, false, true,
 1, 1, 0, 0,
 0, 0, 0, 0, 0,
 0, 0, 0,
 0, 0, 0,
 'Otomasyonlu'),
('tepeoren', 4, 'TEPEÖREN', 'ADAPAZARI', NULL, NULL, 'ABB', 'RTU560CMR01',
 false, false, false, false, true,
 1, 1, 0, 0,
 0, 0, 0, 0, 0,
 0, 0, 0,
 0, 0, 0,
 'Klasik'),
('umraniye', 4, 'ÜMRANİYE', 'ADAPAZARI', NULL, NULL, 'ABB', 'RTU560CMR01',
 false, false, false, false, true,
 1, 1, 0, 0,
 0, 0, 0, 0, 0,
 1, 1, 1,
 2, 0, 0,
 'Klasik'),
('pasakoy', 4, 'PAŞAKÖY', 'ADAPAZARI', NULL, NULL, 'ABB', 'RTU560CMR01',
 false, false, false, false, true,
 1, 1, 0, 0,
 0, 0, 0, 0, 0,
 1, 1, 1,
 2, 0, 0,
 'Klasik'),
('beykoz-gis', 4, 'BEYKOZ GİS', 'ADAPAZARI', NULL, NULL, 'ABB', 'RTU560CMR01',
 false, false, false, false, true,
 1, 1, 0, 0,
 0, 0, 0, 0, 0,
 0, 0, 0,
 0, 0, 0,
 'Klasik'),
('buyukbakkalkoy', 4, 'BÜYÜKBAKKALKÖY', 'ADAPAZARI', NULL, NULL, 'ABB', 'RTU560CMR01',
 false, false, false, false, true,
 1, 1, 0, 0,
 0, 0, 0, 0, 0,
 0, 0, 0,
 0, 0, 0,
 'Klasik'),
('cumhuriyet', 4, 'CUMHURİYET', 'ADAPAZARI', NULL, NULL, 'ABB', 'RTU560CMR01',
 false, false, false, false, true,
 1, 1, 0, 0,
 0, 0, 0, 0, 0,
 0, 0, 0,
 0, 0, 0,
 'Klasik'),
('goztepe-gis', 4, 'GÖZTEPE GİS', 'ADAPAZARI', NULL, NULL, 'ABB', 'RTU560CMR01',
 false, false, false, false, true,
 1, 1, 0, 0,
 0, 0, 0, 0, 0,
 0, 0, 0,
 0, 0, 0,
 'Klasik'),
('kadikoy-gis', 4, 'KADIKÖY GİS', 'ADAPAZARI', NULL, NULL, 'ABB', 'RTU560CMR01',
 false, false, false, false, true,
 1, 1, 0, 0,
 0, 0, 0, 0, 0,
 0, 0, 0,
 0, 0, 0,
 'Klasik'),
('kucukbakkalkoy-gis', 4, 'KÜÇÜKBAKKALKÖY GİS', 'ADAPAZARI', NULL, NULL, 'ABB', 'RTU560CMR01',
 false, false, false, false, true,
 1, 1, 0, 0,
 0, 0, 0, 0, 0,
 0, 0, 0,
 0, 0, 0,
 'Klasik'),
('maltepe-gis-istanbul', 4, 'MALTEPE GİS İSTANBUL', 'ADAPAZARI', NULL, NULL, 'ABB', 'RTU560CMR01',
 false, false, false, false, true,
 1, 1, 0, 0,
 0, 0, 0, 0, 0,
 0, 0, 0,
 0, 0, 0,
 'Klasik'),
('selimiye-gis', 4, 'SELİMİYE GİS', 'ADAPAZARI', NULL, NULL, 'ABB', 'RTU560CMR01',
 false, false, false, false, true,
 1, 1, 0, 0,
 0, 0, 0, 0, 0,
 0, 0, 0,
 0, 0, 0,
 'Klasik'),
('vanikoy-gis', 4, 'VANİKÖY GİS', 'ADAPAZARI', NULL, NULL, 'ABB', 'RTU560CMR01',
 false, false, false, false, true,
 1, 1, 0, 0,
 0, 0, 0, 0, 0,
 0, 0, 0,
 0, 0, 0,
 'Klasik');